management:
  endpoints:
    shutdown:
      enabled: true
endpoints:
  shutdown:
    enabled: true

server:
  port: ${SERVER_PORT:8080}
spring:
  application.name: ${APPLICATION_NAME:spring-security-keycloak-oauth}
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8484/auth/realms/my_realm
        registration:
          keycloak:
            client-id: my_client
           ## client-secret: 234
#          google:
#            client-id: < Enter Google Client ID >
#            client-secret: < Enter Google Client Secret >
#          facebook:
#            client-id: < Enter Facebook App ID >
#            client-secret: < Enter Facebook App Secret >
#          github:
#            client-id: < Enter Github Client ID >
#            client-secret: < Enter Github Client Secret >
#          okta:
#            client-id: < Enter Okta Client ID >
#            client-secret: < Enter Okta Client Secret >